stages:
  - build-app
  - build-docker

build-app-staging:
  stage: build-app
  except:
    - prod
  image: node:18
  variables:
    NEXT_TELEMETRY_DISABLED: "1"
    NEXT_PUBLIC_VERSION: '${CI_COMMIT_SHORT_SHA}'
  script:
    - yarn install --frozen-lockfile --registry https://npm-cache.da-io.net/
    - yarn build:staging
  artifacts:
    paths:
      - .next/
    exclude:
      - .next/cache/**/*
    expire_in: 1 hour

build-app-prod:
  stage: build-app
  only:
    - prod
  image: node:18
  variables:
    NEXT_TELEMETRY_DISABLED: "1"
    NEXT_PUBLIC_VERSION: '${CI_COMMIT_SHORT_SHA}'
  script:
    - yarn install --frozen-lockfile --registry https://npm-cache.da-io.net/
    - yarn build
  artifacts:
    paths:
      - .next/
    exclude:
      - .next/cache/**/*
    expire_in: 1 hour

build-docker:
  stage: build-docker
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN source.da-io.net:4567
    - docker pull source.da-io.net:4567/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$CI_COMMIT_REF_SLUG || true
    - docker build --cache-from source.da-io.net:4567/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$CI_COMMIT_REF_SLUG -t source.da-io.net:4567/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$CI_COMMIT_REF_SLUG .
    - docker push source.da-io.net:4567/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:${CI_COMMIT_REF_SLUG}