export enum Language {
  AFRIKAANS = 'AFRIKAANS',
  ENGLISH = 'ENGLISH',
  ISINDEBELE = 'ISINDEBELE',
  ISIXHOSA = 'ISIXHOSA',
  ISIZULU = 'ISIZULU',
  SEPEDI = 'SEPEDI',
  SESOTHO = 'SESOTHO',
  SETSWANA = 'SETSWANA',
  SISWATI = 'SISWATI',
  TSHIVENDA = 'TSHIVENDA',
  XITSONGA = 'XITSONGA',
}
